recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Enable LEDs for Celestica Questone 2A and adapt SDK to send the expected
data.
* ofdpa: cel-questone-2a: load proper custom_led.bin
* ofdpa: add support for cmicx legacy led data format
* ofdpa: cel-questone-2a: enable legacy led data format
* ofdpa: cel-questone-2a: enable LED linkscan
=> ofdpa: enable LEDS on Questone 2A

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
OF-DPA disabled by default forwarding of non unicast packets in VLANs
(i.e. broad- and multicast), and only selectively enables it when
creating a bridging flow that targets a flood group or a L2 multicast
group.
This is mostly fine, except when removing a bridging flow that targets a
L2 multicast group, OF-DPA will unconditionally disable forwarding
again, potentially breaking any existing flood flows.
Similarily, removing a briding flow will leave forwarding enabled,
regardless of other flows being present or not.
To fix this, add a function for counting the amount of flows enabling
broad- and multicast forwarding, and only disable it if there are none
left.
Fixes enabling multicast breaking DHCP.
=> ofdpa: do not unconditionally enable dropping of non unicast

recipes-extended/ofdpa-grpc/ofdpa-grpc_git.bb, recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Update the SRC_URIs for ofdpa and ofdpa-grpc to point to the v4.1.0 release and add appropriate checksums for all packages.
ofdpa-grpc checksums are identical to 4.0.
=> switch to release 4.1 binaries and add checksums

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Replace all instances off scripts or code extracting the current time
with a check for the environment variable SOURCE_DATE_EPOCH and using
its value instead if set.
This makes the build reproducable, as Yocto will set the
SOURCE_DATE_EPOCH to the top commit's commit date of the OF-DPA
repository.
This will make the resulting opkg package reproducable, which in turn
allows us to have checksums in the open source repository.
To verify that the build is reproducable:
$ bitbake ofdpa
$ sha256sum /tmp/deploy/ipk/.../ofdpa_*.ipk
$ bitbake -c cleansstate ofdpa
$ bitbake ofdpa
$ sha256sum /tmp/deploy/ipk/.../ofdpa_*.ipk
The SHA256 checksum will now be identical.
=> ofdpa: make build reproducable by following SOURCE_DATE_EPOCH

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Add support for Accton AS7726-32X. This is a 32x100G platform, with two additional 10G ports.
This is mostly a standard Trident-3 X7 platform, so it is fairly easy to support. We mostly need to package up the appropriate firmware files as a new package.
The most interesting thing are two 10G ports, that are connected to a multiplexer, which can be switched between the SFP+ ports, and the internal 10G macs of the Intel SoC.
Currently we do not provide a way of using the internal connection, so we assume these are connected to the 10G ports and are regular SFP+ ports.
=> ofdpa: add support for Accton AS7726-32X

recipes-extended/ofdpa-grpc/ofdpa-grpc_git.bb, recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Make use of the predefined variables FEEDDOMAIN and FEEDURIPREFIX to contruct the package source in a generic way that works both with nightly as with release builds.
Depends on https://github.com/bisdn/meta-switch/pull/17
Signed-off-by: Jonas Gorski <jonas.gorski>
=> make use of feed variables for package sources

conf/layer.conf
Warrior is old, and now untested for quite a while, so let's drop
compatibility with it.
=> conf: drop warrior compatibility

recipes-extended/ofdpa-grpc/ofdpa-grpc_git.bb, recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Since we now have a stable build for OF-DPA, the release checksums should not change, so update the packages with the checksums from the latest build packages.
=> update packages with expected release checksums

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
None of the differences are relevant to OF-DPA, so treat AS4610-54T (B)
the same as AS4610-54T.
=> ofdpa: treat AS4610-54T (B) as AS4610-54T

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Update OF-DPA with the latest changes:
* ofdpa_pktrxtx: fix output and error handling
* ofdpa: fix mplsL2Port and tunnelId formatting for client_flowtable_dump 
* ofdpa: propagate learning mode also to l2 station move
=> update ofdpa to latest version

recipes-extended/ofdpa-grpc/ofdpa-grpc_git.bb, recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Harden OF-DPA and ofdpa-grpc against unprivileged accesses to the bcm diag shell:
* require root for accessing the server's unix socket (and thus the server directly)
* verify stp states are valid state names in ofdpa-grpc
=> ofdpa: prevent unprivileged access to the bcm diag shell

recipes-extended/ofdpa-grpc/ofdpa-grpc_git.bb, recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Backport two fixes in preparation for the v4.3.1 release.
Bump the OF-DPA version to just 6.1 to signify that this is r6 with one extra change.
=> v4.3.1: backport fixes

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Update PR to add support for Accton AS4630-54PE and package the firmware files for Trident3-X3 as found on it.
=> add support for Accton AS4630-54PE

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
This PR contains a number of fixes and extensions for ofdpa, including:
* allow setting l2/l3 memory allocation mode
* move bcm.log from /usr/sbin to /var/log
=> ofdpa updates: l2/l3 memory allocation mode; bcm.log

recipes-kernel/openbcm-gpl-modules/files/patches/0009-bcm-knet-fix-race-between-creation-and-open.patch, recipes-kernel/openbcm-gpl-modules/openbcm-gpl-modules_6.5.24.bb
When creating a netif, the netif will be registered and made available
to userspace before its private data is initialized.
This creates a window where accessing the device (e.g. opening it) may
cause a null pointer access since netdev_priv() isn't populated yet.
E.g. bkn_open will get priv->sinfo and access its fields:
```
bkn_open(struct net_device *dev)
{
bkn_priv_t *priv = netdev_priv(dev);
bkn_switch_info_t *sinfo = priv->sinfo;
```
But sinfo is only set *after* the netdev registration:
```
/* calls register_netdev(dev) */
if ((dev = bkn_init_ndev(ma, kmsg->netif.name)) == NULL) {
kmsg->hdr.status = KCOM_E_RESOURCE;
return sizeof(kcom_msg_hdr_t);
}
priv = netdev_priv(dev);
priv->dev = dev;
priv->sinfo = sinfo;
```
This can easily happen if a network manager like systemd-networkd …
=> openbcm-gpl-modules: bcm-knet: fix race between creation and open

recipes-kernel/openbcm-gpl-modules/files/patches/0010-bcm-knet-use-fully-randomized-mac-addresses.patch, recipes-kernel/openbcm-gpl-modules/openbcm-gpl-modules_6.5.24.bb
Instead of using partially randomized mac addresses with a Broadcom OUI
prefix, use fully randomized mac addresses for generated virtualized
Ethernet devices.
To make sure the address is properly tagged as random, switch from
setting dev->dev_addr to using the helper functions
eth_hw_addr_{random,set}. Since these work on an existing device, we
need to move deciding whether to use a random mac into bkn_init_ndev.
Keep the Broadcom OUI prefixed MAC address for the base Ethernet device,
to make it more easily identifiable.
=> openbcm-gpl-modules: bcm-knet: use fully randomized mac addresses

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Adding two commits from internal meta-ofdpa repos:
- ofdpa: do not disable platforms manually
- ofdpa: fix issues found during collection of table sizes
See individual commits for more information on what they do
=> ofdpa: Add two commits from internal repos

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Add missing RDEPENDS for Trident 3 X7 files, which was accidentally
dropped when adding the required changes into the public repo.
Fixes: cef9203a5851 ("ofdpa: package Trident 3 X7 firmware files")
=> ofdpa: add missing RDEPENDS for Trident 3 X7 firmware

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Newer Trident 3 based accton switches use a slightly modified LED data
format, a mix of the old and new formats where the speed is shifted by 1
to make room for the link status.
To properly support it, add a new configuration option
spn_CMCX_LED_ACCTION_DATA to enable this format during runtime, and enable
it for Accton AS4630-54PE.
Fixes setting (Q)SFP status leds with their correct states.
=> ofdpa: accton-as4630-54pe: fix programming SFP leds

conf/layer.conf, recipes-extended/man-pages/man-pages_%.bbappend, recipes-extended/ofdpa-grpc/ofdpa-grpc_git.bb, recipes-kernel/openbcm-gpl-modules/openbcm-gpl-modules_6.5.24.bb, recipes-ofdpa/ofdpa/ofdpa.inc, recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Convert recipes to the new override syntax using
find meta-ofdpa | grep -e '\.bb$' -e '\.inc$' -e '\.conf$' -e '\.bbappend$' | xargs -n 1 ./scripts/contrib/convert-overrides.py
for the basic overrides (append, prepend, remove, ${ARCH}), and manually
replace the machine overrides by hand.
Finally set the layer compatibility to kirkstone.
=> convert layer to kirkstone

recipes-kernel/openbcm-gpl-modules/openbcm-gpl-modules_6.5.24.bb
The correct SPDX compatible license is GPL-2.0-only, so update it.
Fixes the following warning when building when kirkstone:
```
WARNING: openbcm-gpl-modules-6.5.24-r0 do_package_qa: QA Issue: Recipe LICENSE includes obsolete licenses GPLv2 [obsolete-license]
```
=> openbcm-gpl-modules: fix license name

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
brl assumes a custom broadcom linux kernel we don't have, which causes
the ebc tool to get stuck in an endless loop trying to access it.
Instead of patching around it, just pretend we are ubuntu as it does not
trigger any kernel checkout. This is also what we do for all the other
machines.
=> ofdpa: accton-as4610: switch L7 OS to ubuntu

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Now that the ONL package provides a libonlp-platform.so that is a
tangible library with fixed (i.e. no additional) dependencies, we can
drop the explicit link against libonlp-<platform>.
=> Revert "ofdpa: explicitly link against libonlp-platform"

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Link against libonlp and assign consecutive MAC addresses to ports based
on the MAC address stored in the ONIE EEPROM.
For those platforms with more than one preallocated MAC address from the
pool, add platform functions to retrieve the correct amount of MAC
addresses to skip (which is three for all Trident 3 based Edgecore
systems).
=> ofdpa: populate port MAC addresses from ONL

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Parse and pass a MACaddress to KNET when creating netinterfaces. Any
zero mac address will be ignored and only triggers a randomized MAC
address generation.
=> ofdpa: cli: allow setting knet netif MAC addresses

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
The port mapping table for the as5835 is currently sorted by logical
port (mostly). This worked fine until now. However, the newly introduced
code for setting MAC addresses receives the ports in the same order but
assumes they are sorted by the user port number (i.e., the label on the
physical ports on the switch), resulting in the 100 G ports (user ports
49 through 54) picking up MAC addresses from the middle of the range
instead of the last ones.
The result is "ip -br link" reporting something like this:
[...]
port46           DOWN           f8:8e:a1:e0:bb:47 <BROADCAST,MULTICAST>
port47           DOWN           f8:8e:a1:e0:bb:48 <BROADCAST,MULTICAST>
port48           DOWN           f8:8e:a1:e0:bb:49 <BROADCAST,MULTICAST>
port49           DOWN           f8:8e:a1:e0:bb:2e …
=> ofdpa: as5835-54x: sort ports by user (not logical) port

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Switch the L2L3 mode to balanced in the config, as it will give at least the same table sizes, and actually increases them on some platforms.
To make it easier to change one without the other, create separate variables for debug options and l2l3 mode. To still support migrated option sysconf files, also allow OPTIONS, but do not set it as a value in the sysconf file anymore.
Signed-off-by: Jonas Gorski [jonas.gorski@bisdn.de](mailto:jonas.gorski@bisdn.de)
=> ofpda: split up values in /etc/ofdpa/default and use balanced l2l3 mode

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Always apply all patches to OFDPA/SDK to create a unified code base.
To allow the AG5648/AG7648 patches to be applied for non-matching platforms, convert the #ifdef guards to runtime checks for configuration variables, and set the variables for the appropriate platforms. The sole AS4610 patch just adds an appropriate Makefile that has no effect on other targets, and thus can always be applied.
No functional changes.
=> ofdpa: always apply all patches 

recipes-extended/ofdpa-grpc/ofdpa-grpc_git.bb
STG groups are created with all ports in disabled state. This is fine when only working with bridged ports, but for non-bridged ports this means they cannot communicate on these VIDs anymore, and since they are not members of the bridge, they will never get set to forwarding.
Fix this by ensuring all ports are in forwarding by default. The bridge STP will take care of setting all ports to blocking when required.
=> ofdpa-grpc: default stg port state to forwarding

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Properly remap LEDs in the LED processor to fix blinking on activity.
Values taken from
https://github.com/sonic-net/sonic-buildimage/blob/ad6200029f3176eef4d08d519aac7f5ef76f0ac8/device/delta/x86_64-delta_ag5648-r0/led_proc_init.soc.
=> ofdpa: agema-ag5648: fix LED activity

recipes-extended/man-pages/man-pages_%.bbappend
When having both github and gitlab meta-ofdpa in the path, the bbappend will be executed twice. The second execution will already zipped the man pages, so gzip will refuse to create the files.
To avoid this breaking the build, tell gzip to overwrite any existing files. Since the contents of the man pages are identical, there is no harm in doing so.
=> man-pages: force overwrite of potentially existing gz

recipes-kernel/openbcm-gpl-modules/files/patches/0011-bcm-knet-allow-marking-packets-as-offloaded.patch, recipes-kernel/openbcm-gpl-modules/openbcm-gpl-modules_6.5.24.bb
When using KNET interfaces in a bridge, Linux will flood or forward any packets it sees according to default rules. This can be undesirable when the packet was already flooded or forwarded by the switch itself, since this will lead to the packets being duplicated.
To avoid this Linux supports marking packets as forwarding offloaded, which prevents them from being forwarded in software, so add support for marking packets as such.
Since this may break use cases where packets are redirected to the controller, but are expected to be flooded/forwarded in software, make this an optional flag per interface.
=> openbcm-gpl-modules: bcm-knet: allow marking packets as offloaded

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Instead of hardcoding the manufacturer and hardware description in the binary, let's read out the values from ONIE and fill the fields with appropriate values at runtime.
Set the fallback values to "unknown", as we don't know on what hardware we do run in this case.
=> ofdpa: ofagent: fill manufacturer and hardware description from ONIE

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Detect the amount of reserved MAC addresses automatically, and drop the hardcoded values from the platform definitions.
=> ofdpa: autodetect number of reserved MAC addresses instead of hardcoding it

recipes-kernel/openbcm-gpl-modules/files/patches/0001-gmodule-update-proc-code-for-linux-5.6.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0002-kernel-modules-add-dropped-defines-to-work-with-5.9.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0003-linux-kernel-bde-update-API-usage-for-5.10.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0004-bcm-knet-update-API-for-linux-5.6.0.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0005-bcm-knet-strip-vlan-tag-if-received-untagged-at-port.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0006-bcm-knet-report-link-state.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0007-bcm-knet-allow-setting-speed-duplex.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0008-bcm-knet-implement-get_link_ksettings.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0009-bcm-knet-fix-race-between-creation-and-open.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0010-bcm-knet-use-fully-randomized-mac-addresses.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0011-bcm-knet-allow-marking-packets-as-offloaded.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0012-bcm-knet-replace-open-coded-mac-change-code-with-eth.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0013-bcm-knet-update-API-for-kernel-5.19.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0014-linux-kernel-bde-use-platform_get_irq.patch, recipes-kernel/openbcm-gpl-modules/openbcm-gpl-modules_6.5.24.bb
Update the code to compile and work with Linux 6.1.
=> openbcm-gpl-modules: update for linux 6.1

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
When deleting looked up flows (e.g. via cookie), their ID table tree entry was not deleted as their flowId field was not initialized. This eventually lead to the ID table tree running full:
Dec 06 09:07:00 accton-as4610 ofdpa[1016]: ofdbFlowAdd: Flow ID AVL tree full.
Fix this by always initialzing the flowId field when retrieving flows, and add some debug messages to make investigating the issue easier in case it crops up again.
The impact is cosmetic, as nothing ever tries to look up flows by their IDs, but OF-DPA spams the log on each flow deletion/modification attempt.
Fixes #54.
=> ofdpa: fix Flow ID AVL tree entry leak

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Instead of requiring a custom patch for the SDK's ledproc, add support
for setting custom led data formats via an appropriate led command and
a json encoded array of speed/value pairs.
Use this support to replace the custom led patches with appropriate LED
scripts, allowing us to support more formats without requiring patching
the SDK.
Currently this format assumes a very simple speed to LED data value
mapping that is identical for all ports and LED controllers.
If we ever find that we need a more fine grained control, we can always
extend the format.
=> ofdpa: add support for custom led data formats via config

recipes-extended/ofdpa-grpc/ofdpa-grpc.inc, recipes-extended/ofdpa-grpc/ofdpa-grpc_git.bb
Split out all parts required for building from source into its own include file and keep all values needed for the both in the recipe, which then can be identical between internal and public versions.
=> ofdpa-grpc: split out non-common parts into their own include file

recipes-kernel/openbcm-gpl-modules/openbcm-gpl-modules_6.5.24.bb
The linux-kernel-bde module has proper MODULE_DEVICE_TABLE lists both for openflow and pci, so there is no need to force loading it.
So instead of force loading all modules, allow on-demand loading of linux-kernel-bde and add linux-user-bde and linux-bcm-knet as softdeps so they get automatically loaded if linux-kernel-bde gets loaded.
This avoids loading the kernel modules on systems without any Broadcom switches.
=> openbcm-gpl-modules: do not force loading of modules

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
The path /sys/class/net/%s/device/ with a maximum length interface name of 15 is 38 characters. This means we need a buffer of 39 bytes including the terminator, but devPath is only 38 bytes.
This causes interfaces with 15 characters to trigger a buffer overflow, and preventing OF-DPA from startup:
```
Aug 11 10:53:22 delta-ag7648 ofdpa[2210]: platformNumReservedMacsGet: Base MAC = 00:18:23:30:7b:08, num MACs = 4.
Aug 11 10:53:22 delta-ag7648 ofdpa[2210]: platformNumReservedMacsGet: start = 307b08, end = 307b0c
Aug 11 10:53:22 delta-ag7648 ofdpa[2210]: platformNumReservedMacsGet: Interface enp0s20f0 has MAC 00:18:23:30:7b:08.
Aug 11 10:53:22 delta-ag7648 ofdpa[2210]: platformNumReservedMacsGet: ifBase = 307b08
Aug 11 10:53:22 delta-ag7648 ofdpa[2210]: platformNumReservedMacsGet: Updated …
```
=> ofdpa: do not crash on maximum length interface names

recipes-ofdpa/ofdpa/ofdpa-platform/platform/x86-64-accton-as4630-54pe-r0/rc.soc, recipes-ofdpa/ofdpa/ofdpa-platform/platform/x86-64-accton-as5835-54x-r0/rc.soc, recipes-ofdpa/ofdpa/ofdpa-platform/platform/x86-64-accton-as7726-32x-r0/rc.soc, recipes-ofdpa/ofdpa/ofdpa-platform_1.0.bb
To reduce the need for embedded custom_led.bin binaries in OF-DPA, add support for importing these from the SONiC project, and add them for the Edgecore platforms we support.
There is no binary for the Celestica Questone 2A available, so that one still needs one embedded. 
~~Obviously GPL as the license is wrong, so we need to wait for https://github.com/sonic-net/sonic-buildimage/issues/14221 to be addressed before we can merge this.~~
SONiC switched their license to Apache 2.0, so no GPL issue anymore (hooray).
State of LEDs:
* as4630-54pe: LEDs light up for link, no color change for lower speed (always white)
* as5835-54x: LEDs light up after switching to legacy led data
* as7726-32x: LEDs light up as expected
=> ofdpa-platform: import custom_led.bin binaries from SONiC

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
The fields from onie_info aren't fixed length strings, but rather dynamically allocated ones. So we cannot just mempcy them, but need to adhere to their actual length, else we will read over the buffers and copy random data.
Additionally, the OpenFlow spec says that these fields should be null-padded, so use strncpy, which will do that for us if the source string length is less than the destination one.
While at it, make sure we do not try to read from NULL pointers.
Fixes leaking random (static) memory contents into the ofp_desc reply.
Fixes: 2685834c920a ("ofdpa: ofagent: fill manufacturer and hardware description from ONIE")
=> ofdpa: ofagent: fix copying strings from ONIE data

recipes-extended/ofdpa-grpc/ofdpa-grpc_0.5.bb
Update ofdpa-grpc to allow resetting non openflow switch configuration like STP and tunnels (aka VxLAN).
=> ofdpa-grpc: allow resetting switch non openflow configuration

recipes-kernel/openbcm-gpl-modules/files/patches/0015-bcm-knet-extract-and-update-DSCP-for-IP-packets.patch, recipes-kernel/openbcm-gpl-modules/openbcm-gpl-modules_6.5.24.bb
For currently unknown reasons the Broadcom ASIC does not update the DSCP
field for packets sent to controller. But the DMA header does have the
expected DSCP value. So use the DSCP value from the DMA headers [1] to
update IP(v6) packets if set. Luckily there is a linux function for that
which also take care of updating the checksum.
Tested on Helix 4 and Trident3.
[1] https://github.com/Broadcom-Network-Switching-Software/OpenBCM/tree/master/sdk-6.5.24/include/soc/shared/dcbformats
=> openbcm-gpl-modules: bcm-knet: fixup DSCP value in packets to controller

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Actually only one fix, the one for ofagent's ONIE string copy.
=> v5.1.x: assorted fixes from main

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
When creating an VID assignment flow that adds an outer tag, do not just add the tag to untagged packets, but also add it to inner tagged packets (i.e. packets with a different vlan protocol).
This makes the behavior match with the linux behavior of bridges of packets with a different protocol.
E.g. Having the following 802.1ad bridge setup:
$ bridge vlan show
port              vlan-id
port4             100
port5             100 PVID Egress Untagged
Linux behavior:
Sending 802.1q tagged packets in on port5 will make them double tagged, adding a 802.1ad tag based on PVID, then forwarded based on that.
Previous behavior:
Sending 802.1q tagged packets in on port5 get dropped.
New behaviour:
Sending 802.1q tagged packets in on port5 will make them double tagged, adding a 802.1ad tag based on …
=> ofdpa: also add outer tag to inner tagged packets

recipes-ofdpa/ofdpa/ofdpa-platform/platform/arm-accton-as4610-30-r0/config.bcm
Newer SDKs require each port to be dport mapped, and we use the dport mapping to setup the ports in OF-DPA.
Since we didn't setup dport mapping for ports where the dport is identical to the switch's internal port, these ports went missing when going to a newer SDK and the new OF-DPA setup.
Fix this by providing the missing dport mappings.
=> ofdpa-platform: accton-as4610-30: add missing dport definitions

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Like we added the action to add an outer tag to inner tagged packets, we
need to disable it again when removing the flow, so set the action to
bcmVlanActionNone like for the other actions.
=>  ofdpa: disable outer tag for inner tag on vlan flow removal

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Currently, any client using the OF-DPA API adds data to /tmp on every invocation:
* the unix client socket created is never removed
* it appends some logs to /tmp/ofdpa-client.log
Fix the first one by switching the client sockets to abstract sockets, so they don't trigger any file creation.
For the second one, reduce logging by default so that in the normal case no logging messages are generated. These logging messages were only trace messages anyway (entering/exiting function).
=> ofdpa: prevent client utilities from accumuating data in /tmp

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
The mem field DSCP_TABLE does not exist, and calling it causes OF-DPA to crash.
Fix the check based on how the SDK handles it in
src/bcm/esw/port.c:27739-27743
=> ofdpa: fix crash in driverPrioMaxGet() for TD3X

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Newer SDKs require each port to be dport mapped, else they cannot be addressed by unqualified port numbers.
Since we didn't setup dport mapping for ports where the dport is identical to the switch's internal port, these ports wouldn't be configurable e.g. for KNET or other functions that use unqualified port numbers.
Fix this by providing the missing dport mappings.
Fixes: 0ffe6e854c33 ("ofdpa: update SDK to 6.5.21")
=> ofdpa: accton-as4610-30: add missing dport definitions

recipes-extended/ofdpa-grpc/ofdpa-grpc_0.6.bb, recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Expose per port learning configuration via gRPC.
This is needed to implement proper port locking handling.
=> ofdpa: expose per port learning configuration

recipes-extended/ofdpa-grpc/ofdpa-grpc_0.4.1.bb, recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Expose per port learning configuration via gRPC.
This is needed to implement proper port locking handling.
These are backports of https://github.com/bisdn/meta-ofdpa/pull/79 and https://github.com/bisdn/meta-ofdpa/pull/75 (which is unrelated, but allows us to just use the OF-DPA version from main).
=> v4.x: ofdpa: expose per port learning configuration

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
There is no obvious reason why egress vlan flows require L2 unfiltered interface groups, and in limited testing they work fine without it.
So do not treat the absence as an error, but for now warn about it as a reminder that we are leaving expected usage.
=> ofdpa: do not require unfiltered interfaces for egress vlan flows

recipes-kernel/openbcm-gpl-modules/files/patches/0001-gmodule-update-proc-code-for-linux-5.6.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0002-kernel-modules-add-dropped-defines-to-work-with-5.9.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0003-linux-kernel-bde-update-API-usage-for-5.10.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0004-bcm-knet-update-API-for-linux-5.6.0.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0005-bcm-knet-strip-vlan-tag-if-received-untagged-at-port.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0006-bcm-knet-report-link-state.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0007-bcm-knet-allow-setting-speed-duplex.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0008-bcm-knet-implement-get_link_ksettings.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0009-bcm-knet-fix-race-between-creation-and-open.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0010-bcm-knet-use-fully-randomized-mac-addresses.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0011-bcm-knet-allow-marking-packets-as-offloaded.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0012-bcm-knet-replace-open-coded-mac-change-code-with-eth.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0013-bcm-knet-update-API-for-kernel-5.19.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0014-linux-kernel-bde-use-platform_get_irq.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0015-bcm-knet-extract-and-update-DSCP-for-IP-packets.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0016-bcm-knet-fix-reported-tx-bytes.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0017-bcm-knet-switch-to-stat64.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0018-kcom-add-a-message-for-pushing-hw-counters-to-netifs.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0019-bcm-knet-expose-hw-counters-on-port-netifs.patch, recipes-kernel/openbcm-gpl-modules/openbcm-gpl-modules_6.5.24.bb
In order to expose hardware counters via standard interfaces, allow pushing counters via the SDK knet interface to created port interfaces.
These then get exposed via the normal counters, while the "old" software counters are now exposed as cpu_hit offload counters:
```
accton-as4610-54:~$ ip stats show dev port2
8: port2: group offload subgroup hw_stats_info
l3_stats off used off
8: port2: group afstats subgroup mpls
8: port2: group link
RX:  bytes packets errors dropped  missed   mcast
340       4      0       1       0       4
TX:  bytes packets errors dropped carrier collsns
2578      23      0       0       0       0
8: port2: group offload subgroup l3_stats off used off
8: port2: group offload subgroup cpu_hit
RX:  bytes packets errors dropped  missed   mcast
250       3      0 …
```
=> openbcm-gpl-modules: allow pushing hw counters to knet interfaces

recipes-extended/ofdpa-grpc/ofdpa-grpc_0.7.bb, recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
With using KNET, rx rates higher than the default of 1024 pps are easily
achievable. To allow setting these dynamically, expose the SDK API
function as an OF-DPA API function and via gRPC.
=> ofdpa(-grpc): expose bcm_rx_rate_set() 

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Currently we handle local multicast traffic via ACL rules. This has two unwanted side effects:
* Traffic that would have been dropped otherwise is still counted as dropped
* Traffic that would have been forwarded otherwise is still counted as forwarded
To fix this, make use of the ability of creating "BPDU" L2 cache entries in the switch ASIC.
These entries are never forwarded, do not count as dropped, and enable the BPDU bit in packet headers then available for KNET.
The closes equivalent to these entries are Termination MAC entries, which already use L2 cache entries if L2 station entries are not available. So create a new "classification" for Termination MAC entries that are treated as BPDU:
* EtherType matched is ETH_P_ALL (0x0003)
* MAC address matched is in the range 01:80:2c:* or …
=> ofdpa: allow creating termination MAC entries for local multicast traffic

recipes-kernel/openbcm-gpl-modules/files/patches/0001-gmodule-update-proc-code-for-linux-5.6.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0002-kernel-modules-add-dropped-defines-to-work-with-5.9.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0003-linux-kernel-bde-update-API-usage-for-5.10.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0004-bcm-knet-update-API-for-linux-5.6.0.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0005-bcm-knet-strip-vlan-tag-if-received-untagged-at-port.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0006-bcm-knet-report-link-state.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0007-bcm-knet-allow-setting-speed-duplex.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0008-bcm-knet-implement-get_link_ksettings.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0009-bcm-knet-fix-race-between-creation-and-open.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0010-bcm-knet-use-fully-randomized-mac-addresses.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0011-bcm-knet-allow-marking-packets-as-offloaded.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0012-bcm-knet-replace-open-coded-mac-change-code-with-eth.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0013-bcm-knet-update-API-for-kernel-5.19.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0014-linux-kernel-bde-use-platform_get_irq.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0015-bcm-knet-extract-and-update-DSCP-for-IP-packets.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0016-bcm-knet-fix-reported-tx-bytes.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0017-bcm-knet-switch-to-stat64.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0018-kcom-add-a-message-for-pushing-hw-counters-to-netifs.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0019-bcm-knet-expose-hw-counters-on-port-netifs.patch, recipes-kernel/openbcm-gpl-modules/files/patches/0020-bcm-knet-do-not-mark-BPDU-packets-as-offloaded.patch, recipes-kernel/openbcm-gpl-modules/openbcm-gpl-modules_6.5.24.bb
BPDU packets are trapped to controller and never forwarded, so do not mark them as offloaded. This allows them to be forwarded/flooded in software if needed.
Note that this requires configuring the switch ASIC to mark traffic as BPDU via appropriate L2 cache entries, and there is no inherent automatic classification.
=> openbcm-gpl-modules: bcm-knet: do not mark BPDU packets as forwarded

recipes-ofdpa/ofdpa/ofdpa_3.0.5.0-EA5.bb
Like creating BPDU termination MAC flows need to be delegated to the L2 cache entries, deleting them must also be delegated as well.
So forward the deletion request to driverTermMacEntryL2Delete() if the flags are empty (which they will only be for BPDU flows.
Before:
```
$ sudo client_cfg_purge
Purging flow tables.
No entries found in tableId 210
...
No entries found in tableId 17
Error returned from ofdpaFlowDelete: rc = -27, tableId = 20
Error returned from ofdpaFlowDelete: rc = -27, tableId = 20
Error returned from ofdpaFlowDelete: rc = -27, tableId = 20
Deleted 3 flows from tableId 20
No entries found in tableId 24
...
$ client_flowtable_dump
No flow entries found.
$ sudo client_drivshell l2 cache show
509 : mac=09:00:2b:00:00:04/ff:ff:ff:ff:ff:fe vlan=0/0x000 modid=0 port=0/cpu0 …
```
=> ofdpa: fix deletion of BPDU termination MAC flows
